### ISSUE TITLE
OperationalError when running query

### ISSUE THREAD

**Issue by gangtao** [timeplus-io/proton-python-driver#49]
**Describe the bug**

A error was reported from user:

```
Hi,
Thank you for getting back to me! Below are the details you requested:
Helm Chart Version:I have installed Timeplus Enterprise v3.0.7, as shown in the Helm list output. The app version is 2.4.23.
Kubernetes Distribution, Version, and Storage Class:
Kubernetes Distribution: I'm using DigitalOcean Kubernetes.
Kubernetes Version: v1.24.10.
Storage Class: I used do-block-storage-retain as the storage class for both stream and history, with a size of 20Gi each, as specified in the values.yaml.
Socket Error:
Traceback (most recent call last):
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/connection.py", line 325, in connect
  return self._init_connection(host, port)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/connection.py", line 289, in initconnection
  self.socket = self._create_socket(host, port)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/connection.py", line 261, in createsocket
  raise err
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/connection.py", line 252, in createsocket
  sock.connect(sa)
TimeoutError: timed out
Traceback (most recent call last):
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/dbapi/cursor.py", line 111, in execute
  response = execute(
        ^^^^^^^^
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/client.py", line 284, in execute
  with self.disconnect_on_error(query, settings):
 File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in enter
  return next(self.gen)
      ^^^^^^^^^^^^^^
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/client.py", line 227, in disconnect_on_error
  self.connection.force_connect()
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/connection.py", line 219, in force_connect
  self.connect()
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/connection.py", line 346, in connect
  raise err
proton_driver.errors.SocketTimeoutError: Code: 209. (timeplusd-svc.dochio.life:8463)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
 File "/Users/sandydasari/Downloads/freelancer/marcus/repos/jupiter_token_proton/examples/TimeplusDataQuery/execute_normal_query.py", line 10, in <module>
  cursor.execute(query_sql)
 File "/Users/sandydasari/Downloads/freelancer/marcus/nvenv/lib/python3.12/site-packages/proton_driver/dbapi/cursor.py", line 117, in execute
  raise OperationalError(orig)
proton_driver.dbapi.errors.OperationalError: Code: 209. (timeplusd-svc.dochio.life:8463)
```
code :

```python
from proton_driver import connect

account = 'default'


def query(conn):
    query_sql = """select raw:pair_address as pair_address from trending_pairs_5m5m """
    cursor = conn.cursor()
    cursor.set_stream_results(stream_results=True, max_row_buffer=100)
    cursor.execute(query_sql)
    return cursor


def fetch_result(cursor):
    while True:
        data = (cursor.fetchmany(size=100))  # BATCH SIZE
        print(data)  # use the data


def main():
    conn = connect(
        f"proton://default:@localhost:8463/default")
    cursor = query(conn)
    fetch_result(cursor)
    cursor.close()
    conn.close()


if __name__ == "__main__":
    main()

```

**Comment by gangtao** [comment]
I made a test on append only stream which seems working.
need more information about how the stream is created
